---
- name: Install node.js and npm
  yum: name=npm state=present enablerepo=epel

- name: Install node.js and npm
  npm: name={{ item }} global=yes state=present
  with_items: '{{node_npm_modules}}'
